# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: sqlite3
  encoding: utf8
  database: development_e_shop
  username: username
  password: password
  host: 127.0.0.1

test:
  adapter: sqlite3
  encoding: utf8
  database: test_e_shop
  username: username
  password: password
  host: 127.0.0.1



